# -*- coding: utf-8 -*-
"""Codeforinput.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OzsiKFu6BZiKYfZo2bojZThjZ6mQJJFm

This is the Python notebook for generation of datasets.
"""

!pip install faker

import uuid
import csv
from faker import Faker
from random import choice
fake = Faker()
expertList = [
    "Novice",
    "Beginner",
    "Intermediate",
    "Expert"
]
rlist=[
  "Ilottery",
  "Product",
  "Americas",
  "International",
  "Casino"
]
ylist=[
  "0 to 3 years",
  "4 to 8 years",
  "4 to 8 years",
  "16years and above"

]
tlist=[
  "Java/J2EE",
  " Testing",
 "Automation"
 ".NET/C#"
 "C++"

]
dataset = []
generated_ids = set()
generated_names = set()
generated_addresses = set()

while len(dataset) < 1000000:
    name = fake.name()
    address = fake.address()
    id = str(uuid.uuid4())

    if id not in generated_ids and name not in generated_names and address not in generated_addresses:
        dataset.append({"Name": name,
                        "Address": address,
                        "ID": id,
                        "Skill":choice(expertList),
                        "region":choice(rlist),
                        "year":choice(ylist),
                        "technology":choice(tlist)
                       })
        generated_ids.add(id)
        generated_names.add(name)
        generated_addresses.add(address)
filename = 'data.csv'

with open(filename, 'w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=dataset[0].keys())
    writer.writeheader()
    writer.writerows(dataset)

print(f'{filename} created successfully.')
from google.colab import files
files.download("data.csv")

